; Inno Setup Installer Template for APC Plugins
; This script is generated by the Ship workflow
; 
; Placeholders:
;   {#PluginName}     - Plugin name / CMake target name (e.g., CloudWash)
;   {#ProductName}    - Actual bundle/binary name from PRODUCT_NAME in CMakeLists.txt
;                       (defaults to {#PluginName} when the two are the same, e.g.
;                       "VRS Vocal Comp" for target VictorRSwagVocalComp)
;   {#PluginVersion}  - Version (e.g., 1.0.0)
;   {#CompanyName}    - Company name (e.g., APC)
;   {#PluginURL}      - Plugin website URL
;   {#ReleaseDir}     - Absolute ship/output directory (from paths.release_dir)
;   {#BuildDir}       - Absolute build directory (from paths.build_dir)
;   {#PluginsDir}     - Absolute plugins directory (from paths.plugins_dir)
;   {#IconPath}       - Absolute path to icon.ico (empty if missing)
;   {#SetupIconLine}  - Full SetupIconFile= line, or empty if no icon

#define PluginName "{#PluginName}"
#define ProductName "{#ProductName}"
#define PluginVersion "{#PluginVersion}"
#define CompanyName "{#CompanyName}"
#define PluginURL "{#PluginURL}"

[Setup]
; Basic installer information
AppId={{{#PluginName}-APC-Plugin}
AppName={#PluginName}
AppVersion={#PluginVersion}
AppPublisher={#CompanyName}
AppPublisherURL={#PluginURL}
AppSupportURL={#PluginURL}
AppUpdatesURL={#PluginURL}
DefaultDirName={commoncf}\VST3\{#ProductName}.vst3
DisableDirPage=no
DefaultGroupName={#PluginName}
DisableProgramGroupPage=yes

; Output settings
OutputDir="{#ReleaseDir}"
OutputBaseFilename={#PluginName}-{#PluginVersion}-Windows-Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
LicenseFile="{#ReleaseDir}/LICENSE.txt"

; Appearance
{#SetupIconLine}
UninstallDisplayIcon={commoncf}\VST3\{#ProductName}.vst3\icon.ico
UninstallDisplayName={#PluginName} {#PluginVersion}

; 64-bit installation (forces Program Files, not Program Files (x86))
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

; Security
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=dialog

; Version info
VersionInfoVersion={#PluginVersion}
VersionInfoCompany={#CompanyName}
VersionInfoDescription={#PluginName} Audio Plugin
VersionInfoProductName={#PluginName}
VersionInfoProductVersion={#PluginVersion}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Types]
Name: "full"; Description: "Full installation"
Name: "custom"; Description: "Custom installation"; Flags: iscustom

[Components]
Name: "vst3"; Description: "VST3 Plugin"; Types: full custom; Flags: fixed
Name: "standalone"; Description: "Standalone Application"; Types: full custom
Name: "presets"; Description: "Factory Presets"; Types: full custom
Name: "documentation"; Description: "Documentation"; Types: full custom

[Dirs]
; Create directories for presets and settings
Name: "{commonappdata}\{#PluginName}\Presets"; Components: presets
Name: "{userappdata}\{#PluginName}"; Components: vst3 standalone

[Files]
; VST3 Plugin
Source: "{#BuildDir}/plugins/{#PluginName}/{#PluginName}_artefacts/Release/VST3/{#ProductName}.vst3\*"; \
    DestDir: "{app}"; \
    Components: vst3; \
    Flags: ignoreversion recursesubdirs createallsubdirs

; Icon for uninstaller display
Source: "{#PluginsDir}/{#PluginName}/Assets/icon.ico"; \
    DestDir: "{app}"; \
    Components: vst3; \
    Flags: ignoreversion skipifsourcedoesntexist

; Standalone Application
Source: "{#BuildDir}/plugins/{#PluginName}/{#PluginName}_artefacts/Release/Standalone/{#ProductName}.exe"; \
    DestDir: "{autopf}\{#PluginName}"; \
    Components: standalone; \
    Flags: ignoreversion

; Copy icon.ico to standalone folder for shortcut icons
Source: "{#PluginsDir}/{#PluginName}/Assets/icon.ico"; \
    DestDir: "{autopf}\{#PluginName}"; \
    Components: standalone; \
    Flags: ignoreversion skipifsourcedoesntexist

; Presets (optional - only if they exist)
Source: "{#PluginsDir}/{#PluginName}/Presets\*"; \
    DestDir: "{commonappdata}\{#PluginName}\Presets"; \
    Components: presets; \
    Flags: recursesubdirs createallsubdirs skipifsourcedoesntexist

; Documentation - Auto-include ALL files from Documentation folder
; This goes INSIDE the plugin bundle, not in VST3 root (keeps VST3 folder clean)
Source: "{#PluginsDir}/{#PluginName}/Documentation\*"; \
    DestDir: "{app}\Documentation"; \
    Components: documentation; \
    Flags: recursesubdirs createallsubdirs skipifsourcedoesntexist ignoreversion

; Also copy documentation to Standalone folder (if standalone is installed)
Source: "{#PluginsDir}/{#PluginName}/Documentation\*"; \
    DestDir: "{autopf}\{#PluginName}\Documentation"; \
    Components: standalone documentation; \
    Flags: recursesubdirs createallsubdirs skipifsourcedoesntexist ignoreversion

; Root-level license files (required for compliance)
Source: "{#ReleaseDir}/LICENSE.txt"; \
    DestDir: "{app}\Documentation"; \
    Components: documentation; \
    Flags: ignoreversion skipifsourcedoesntexist

Source: "{#RepoRoot}/CHANGELOG.md"; \
    DestDir: "{app}\Documentation"; \
    Components: documentation; \
    Flags: ignoreversion skipifsourcedoesntexist

[Icons]
; Start Menu shortcuts
Name: "{group}\{#PluginName}"; \
    Filename: "{autopf}\{#PluginName}\{#ProductName}.exe"; \
    IconFilename: "{autopf}\{#PluginName}\icon.ico"; \
    Components: standalone

Name: "{group}\User Manual"; \
    Filename: "{app}\Documentation\USER_MANUAL.md"; \
    Components: documentation

Name: "{group}\Documentation Folder"; \
    Filename: "{app}\Documentation"; \
    Components: documentation

Name: "{group}\Uninstall {#PluginName}"; \
    Filename: "{uninstallexe}"

; Desktop shortcut (optional, user can uncheck)
Name: "{autodesktop}\{#PluginName}"; \
    Filename: "{autopf}\{#PluginName}\{#ProductName}.exe"; \
    IconFilename: "{autopf}\{#PluginName}\icon.ico"; \
    Components: standalone; \
    Tasks: desktopicon

[Tasks]
Name: "desktopicon"; \
    Description: "{cm:CreateDesktopIcon}"; \
    GroupDescription: "{cm:AdditionalIcons}"; \
    Components: standalone

[Run]
; Launch after installation (optional)
Filename: "{autopf}\{#PluginName}\{#ProductName}.exe"; \
    Description: "Launch {#PluginName}"; \
    Flags: postinstall skipifsilent nowait; \
    Components: standalone

[UninstallDelete]
; Clean up user data on uninstall (optional - commented out to preserve user data)
; Type: filesandordirs; Name: "{userappdata}\{#PluginName}"

[Code]
// Custom installation logic

// Check if running as administrator
function InitializeSetup(): Boolean;
begin
  if not IsAdmin then begin
    MsgBox('This installer requires administrator privileges to install VST3 plugins.', mbError, MB_OK);
    Result := false;
  end else begin
    Result := true;
  end;
end;

// Custom page to show installation summary
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then begin
    // Log installation success
    Log('Installation completed successfully');
  end;
end;

// Validate installation path
function NextButtonClick(CurPageID: Integer): Boolean;
var
  Vst3Path: string;
begin
  Result := true;
  
  if CurPageID = wpSelectDir then begin
    Vst3Path := ExpandConstant('{commoncf}\VST3');
    
    // Warn if not installing to standard VST3 location
    if Pos(Vst3Path, WizardDirValue) = 0 then begin
      if MsgBox('You are not installing to the standard VST3 location (' + Vst3Path + '). ' +
                'Your DAW may not detect the plugin. Continue anyway?',
                mbConfirmation, MB_YESNO) = IDNO then
      begin
        Result := false;
      end;
    end;
  end;
end;

[Messages]
; Custom messages
WelcomeLabel2=This will install [name] [version] on your computer.%n%nThe plugin includes VST3 format for use in your DAW, and a standalone application.%n%nIt is recommended that you close all DAW applications before continuing.
FinishedLabel=Setup has finished installing [name] on your computer. You may need to restart your DAW for the plugin to appear.
